server:
  port: 8078
mark:
  uploadPath: D:/var/uploaded_files/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mark?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
ip:
  localhost: 127.0.0.1
logging:
  level:
    com.dk: debug
